steps:
- name: gcr.io/cloud-builders/gcloud
  args: ['functions', 'deploy', 'test_${_NAME}', '--entry-point=hello_world', '--runtime=python37','--trigger-http', '--project=${_PROJECT_ID}']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash 
  args: ['test.sh']
- name: gcr.io/cloud-builders/gcloud
  args: ['functions', 'deploy', '${_NAME}', '--entry-point=hello_world', '--runtime=python37','--trigger-http', '--project=${_PROJECT_ID}']
